name: Test Earth Engine Script

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install earthengine-api

    - name: Run Earth Engine Script
      env:
        EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}
      run: |
        python ee-test-with-oauth2.py
